version: "3"
services:
  site:
    image: postgres
    container_name: 'pg_container_2'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432" 
    volumes:
      - "./db:/var/lib/postgresql/how_data:z"
  bi:
    image: metabase/metabase
    ports: 
     - "3000:3000"
    links:
     - site    